services:
  mongo:
    image: mongo:7
    container_name: bugscope-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: bugscope-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/bugscope
      - API_KEY=bugscope_super_secret_key_123
    depends_on:
      - mongo

volumes:
  mongo_data: